"""Phase 1: stock_master + daily_ohlcv

Revision ID: e09b66424886
Revises:
Create Date: 2026-02-28 17:18:55.334523

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e09b66424886"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_ohlcv",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("high", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("low", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("close", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("trading_value", sa.Numeric(precision=20, scale=0), nullable=True),
        sa.Column("change_rate", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "date", name="uq_daily_ohlcv_symbol_date"),
    )
    op.create_index("ix_daily_ohlcv_symbol", "daily_ohlcv", ["symbol"], unique=False)
    op.create_table(
        "stock_master",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("market_type", sa.String(length=20), nullable=False),
        sa.Column("standard_code", sa.String(length=20), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("listed_shares", sa.BigInteger(), nullable=True),
        sa.Column("market_cap_krw", sa.Numeric(precision=20, scale=0), nullable=True),
        sa.Column("face_value", sa.Numeric(precision=15, scale=0), nullable=True),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_master")
    op.drop_index("ix_daily_ohlcv_symbol", table_name="daily_ohlcv")
    op.drop_table("daily_ohlcv")
    # ### end Alembic commands ###
